angular.module('ProELearning.directives',[]).directive('owlCarousel',['$timeout',function($timeout){return{restrict:'E',transclude:!1,link:function(scope,element){var defaultOptions={loop:!1,autoplay:!0,autoplayHoverPause:!0,autoplayTimeout:2000,nav:!0,rewind:!0,margin:20,navText:["<i class='fa fa-angle-left' aria-hidden='true'></i>","<i class='fa fa-angle-right' aria-hidden='true'></i>"],dots:!1,navSpeed:300,owl2row:!0,owl2rowTarget:'item',owl2rowContainer:'owl2row-item',owl2rowDirection:'utd',responsiveClass:!0,responsive:{0:{items:1},501:{items:2},731:{items:2},769:{items:3},993:{items:4},1201:{items:4},1441:{items:6}}};scope.initCarousel=function(element){jQuery(element).owlCarousel(defaultOptions)};$timeout(function(){jQuery(element).owlCarousel(defaultOptions)
scope.initCarousel()},0,!1)}}}]).directive('owlCarouselTestimonials',['$timeout',function($timeout){return{restrict:'E',transclude:!1,link:function(scope,element){var defaultOptions={loop:!1,autoplay:!0,autoplayHoverPause:!0,autoplayTimeout:2000,nav:!1,rewind:!0,margin:0,navSpeed:300,items:1,};scope.initCarousel=function(element){jQuery(element).owlCarousel(defaultOptions)};$timeout(function(){jQuery(element).owlCarousel(defaultOptions)
scope.initCarousel()},0,!1)}}}]).directive('owlCarouselItem',[function(){return{restrict:'A',transclude:!1,link:function(scope,element){if(scope.$last){scope.initCarousel(element.parent())}}}}]).directive('showTab',function(){return{link:function(scope,element,attrs){element.on("click",function(e){e.preventDefault();$(element).tab('show')})}}}).directive('modal',function Directive(ModalService){return{link:function(scope,element,attrs){if(!attrs.id){console.error('Modal must have an ID.');return}
var modal={id:attrs.id,open:Open,};ModalService.Add(modal);scope.$on('$destroy',function(){ModalService.Remove(attrs.id);element.remove()});function Open(){element.show();$('body').addClass('modal-open')}}}}).directive('fileInput',['$parse',function($parse){return{restrict:'A',link:function(scope,elem,attrs){elem.bind('change',function(){$parse(attrs.fileInput).assign(scope,elem[0].files);scope.$apply()})}}}]).directive('animateNumbers',function($timeout){return{restrict:'A',replace:!1,scope:!0,link:function(scope,element,attrs){var e=element[0];var refreshInterval=30;var duration=1000;var number=parseInt(e.innerText);var step=0;var num=0;var steps=Math.ceil(duration/refreshInterval);var increment=(number/steps);var percentCompleted=0;var lastNumberSlowCount=3;if(number>lastNumberSlowCount){number=number-lastNumberSlowCount}
scope.timoutId=null;var counter=function(){scope.timoutId=$timeout(function(){num+=increment;percentCompleted=Math.round((num/number)*100);if(percentCompleted>60&&percentCompleted<80){refreshInterval=refreshInterval+10}
else if(percentCompleted>90){refreshInterval=200}
step++;if(step>=steps){$timeout.cancel(scope.timoutId);num=number;e.textContent=number;if(number>lastNumberSlowCount){slowCounter()}}else{e.textContent=Math.round(num);counter()}},refreshInterval)}
var slowCounter=function(){scope.timoutId=$timeout(function(){lastNumberSlowCount --;if(lastNumberSlowCount<0){$timeout.cancel(scope.timoutId)}
else{number++;e.textContent=number;slowCounter()}},300)}
counter();return!0}}}).directive('toggle',function(){return{restrict:'A',link:function(scope,element,attrs){if(attrs.toggle=="tooltip"){$(element).tooltip()}
if(attrs.toggle=="popover"){$(element).popover()}}}}).directive("disableContextmenuCutCopyPaste",function(){return{restrict:'A',scope:{},link:function(scope,element){element.on('cut copy paste contextmenu',function(event){event.preventDefault()})}}}).directive('slideable',function(){return{restrict:'C',compile:function(element,attr){var contents=element.html();element.html('<div class="slideable_content" style="margin:0 !important; padding:0 !important" >'+contents+'</div>');return function postLink(scope,element,attrs){attrs.duration=(!attrs.duration)?'1s':attrs.duration;attrs.easing=(!attrs.easing)?'ease-in-out':attrs.easing;element.css({'overflow':'hidden','height':'150px','transitionProperty':'height','transitionDuration':attrs.duration,'transitionTimingFunction':attrs.easing})}}}}).directive('slideToggle',function(){return{restrict:'A',link:function(scope,element,attrs){var target=document.querySelector(attrs.slideToggle);attrs.expanded=!1;element.bind('click',function(){var content=target.querySelector('.slideable_content');if(!attrs.expanded){content.style.border='1px solid rgba(0,0,0,0)';var y=content.clientHeight+40;content.style.border=0;target.style.height=y+'px'}else{target.style.height='150px'}
attrs.expanded=!attrs.expanded})}}})